baseURL = "http://zeal.co/"
languageCode = "en-us"
title = "ZEAL.CO"
ignorefiles = [ "Templates/*" ]
enableGitInfo = true
summaryLength = 10
googleAnalytics = "333696126"


# this post discusses a use for this:
# https://blog.bobhy.com/blog/lessons-learned-in-hugo-config/
# [permalinks]
    # notebook = "/notebook/:slug"

[frontmatter]
  date = ['date', 'publishDate', 'lastmod']
  expiryDate = ['expiryDate']
  lastmod = ['lastmod', ':fileModTime', 'date', 'publishDate']
  # git was giving the same lastmod time to all notebook files
  # lastmod = [':git', 'lastmod', ':fileModTime', 'date', 'publishDate']
  publishDate = ['publishDate', 'date']
